Category.create(name:"HTML")
Category.create(name:"CSS")
Category.create(name:"Ruby")
Category.create(name:"Ruby on Rails")
Category.create(name:"Javascript")
Category.create(name:"jQuery")
Category.create(name:"PHP")